In [2]:
# numpy is a fundamental library for scientific computing, it provides the support for arrays and matrices along with mathematical functions to operate on that data strucutres


In [3]:
import numpy as np



In [4]:
print(dir(np))

['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__array_namespace_info__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_array_api_info', '_core', '_distributor_init', '_expired_attrs_2_0', '_globals', '_int_extended_msg', '_mat', '_msg', '_pyinstaller_hooks_dir', '_pytesttester', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_equiv', 'array_repr', 'array_split'

In [5]:
# creating a array using numpy

arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.shape)  # prints (5,) which depicts a 1-D array

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [6]:
# converting a 1-D array into a 2-D array

ar1 = np.array([1,2,3])
arr2 = ar1.reshape(1,3)
print(arr2) # arr2 is a 2d array
print(arr2.shape)  # prints (1,3) which is a 2-D array

[[1 2 3]]
(1, 3)


In [7]:
l = np.array([[1,2,4],
             [5,6,7]])
print(l)
print(l.shape)

[[1 2 4]
 [5 6 7]]
(2, 3)


In [8]:
arr1 = np.array([[1,2,34,5,8],[5,6,7,9,10]])
print(arr1)

[[ 1  2 34  5  8]
 [ 5  6  7  9 10]]


In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
np.arange(0,12,2).reshape([6,1])

array([[ 0],
       [ 2],
       [ 4],
       [ 6],
       [ 8],
       [10]])

In [11]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
# identiy matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
# numpy vectorized operations

arr1 = np.array([1,2,34,2])
arr2 = np.array([3,4,5,7])

#Element wise addition
print(arr1+arr2)

# Element wise subtration
print(arr1-arr2)

# Element wise multiplication
print(arr1*arr2)

[ 4  6 39  9]
[-2 -2 29 -5]
[  3   8 170  14]


In [14]:
# Univeral funtions

arr =np.array([1,2,3,4])
print(np.sqrt(arr))  # square root of each and every element

# exponential function using numpy
print(np.exp(arr))


# Sin,cos operation

print(np.sin(arr))
print(np.cos(arr))



[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [20]:
import numpy as np

arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print("Array is:\n", arr)

# First row
print("First row:", arr[0])

# Last 2 rows
print("Last 2 rows:\n", arr[1:])

# Rows 1 onwards, columns 2 onwards
print("arr[1:, 2:]:\n", arr[1:, 2:])

# This was incorrect logic in your code
# arr[0:][2:] is confusing → equivalent to arr[2:]
print("arr[2:]:\n", arr[2:])

# First element
print("First element:", arr[0, 0])


print(arr[1:,1:3])

Array is:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First row: [1 2 3 4]
Last 2 rows:
 [[ 5  6  7  8]
 [ 9 10 11 12]]
arr[1:, 2:]:
 [[ 7  8]
 [11 12]]
arr[2:]:
 [[ 9 10 11 12]]
First element: 1
[[ 6  7]
 [10 11]]


In [23]:
# modifying array elements

arr[0][0] =100
arr

arr[1:]=100
arr


array([[100,   2,   3,   4],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [ ]:
# Normalization using numpy
# change data to have mean=0 and stdev=1 this concept is called as normalization



data = np.array([1,2,3,4,5])
mean = np.mean(data)
stdev = np.std(data)


normalized = (data-mean)/stdev
print("normalized data",normalized)

normalized data [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [40]:
# logical operations

data = np.array([1,2,3,5,6,7,8,9,10])

data>5 # this return a boolean lst of the indices that have values greater than 5


data[data>5]  # this returns a array of datavalues that are grater than 5

data[(data>5) & (data<10)] # using multiple conditions use the logical operators


array([6, 7, 8, 9])